import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";

// ✅ Initialize the Inter font
const inter = Inter({ subsets: ["latin"] });

/*
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
*/

export const metadata: Metadata = {
    title: "Portfolio 2.0",
    description: "Generated by Portfolio 2.0",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                className={inter.className}
            >
                {children}
            </body>
        </html>
    );
}
